name: Release & Publish Binaries

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: read
  issues: read
  repository-projects: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.10.0'

      - name: Install semantic-release
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release