name: StructuraLens
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MY_APP_ID }}
          private-key: ${{ secrets.MY_APP_PRIVATE_KEY }}
          owner: "andy-c-jones"
          repositories: "StructuraLens"
      - uses: andy-c-jones/StructuraLensAction@v1
        with:
          solution: StructuraLens.slnx
          github-token: ${{ steps.generate-token.outputs.token }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
